### ISSUE TITLE
Can DREAM support multi-threads mode?

### ISSUE THREAD

**Issue by shangguandong1996** [jernst98/STEM_DREM#4]
Hi, dear developer
I am using DREAM, but I find its speed is very low. It may takes several hours(maybe 10+h) to complete the whole process.
My gene expression data is 22055(gene) * 6(time) (I have filtered some genes by myself), while my TF-gene interaction data is 2M. I think maybe my TF-interaction is too much so the DREAM runs slowly. So I am wondering DREAM whether support multi-threads mode so I can improve software running speed :)

The TF-gene interaction data is from https://agris-knowledgebase.org/downloads.html, which is the update version of arabidopsis_agris your 2012 DREAM  2.0 paper mentioned.

And thanks agian for this wonderful tools.

Best wishes 
Guandong Shang

**Comment by jernst98** [comment]
Hi Guandong,

You may want to consider filtering your gene set more to focus only on genes that substantially change gene expression. This can both reduce runtime and focus more of the modeling power on genes that show a greater change in expression level.

When run in interactive mode, DREM also allows you to preview the current model while it is running and typically the major branches are found relatively quickly. Alternatively, DREM allows running in batch mode so you can let it run overnight and if you are learning multiple different DREM models each can be learned on a different processor. Otherwise DREM doesn't currently have explicit support for multi-thread parallel processing. 

Best,
-Jason

**Comment by shangguandong1996** [comment]
Thanks for your reply :) Dr Ernst.
I have another question. When I run in GUI mode, Can I save the whole results of DREAM output like `save` and `load` function in R studio. 
I have tried to save mode, but it seems just save the mode paramter I used in txt.  
Please forgive me if I missed something.

Guandong Shang

**Comment by jernst98** [comment]
You can save the DREM parameter settings by clicking on the disk icon. 
DREM can be started using those settings by specifying '-d filename'
at the command line where filename is the file with the saved parameter
settings. Note that this is separate than saving the model parameters.

**Comment by shangguandong1996** [comment]
I see it :)
but If I want to share my DREAM results to others, they have to run the DREAM agian using my saved seeting instead of quickly loading the whole results?

**Comment by jernst98** [comment]
What results are you referring to? If you open DREM with the saved parameter settings and load the saved model parameters then you will get the same results DREM does not need to go through the model search again so it is quick. You can also save separately the contents of individual output tables you are interested in.

**Comment by shangguandong1996** [comment]
get it :) 
I am sorry I mixed the paramters setting and model paramters at first, and thanks again for your reply.
